def generate_report(
    monitoring,
    rca,
    automation,
    security
):

    report = f"""
INFRA MIND AI INCIDENT REPORT
=============================

MONITORING ANALYSIS
-------------------
{monitoring}

ROOT CAUSE ANALYSIS
-------------------
{rca}

AUTOMATION RECOMMENDATIONS
--------------------------
{automation}

SECURITY VALIDATION
-------------------
{security}

Generated by InfraMind AI
"""

    return report